Pass ICU linker flags to testapp
After a system upgrade, I couldn't build/run the tests anymore.
The ICU linker flags that icu-config gives us need to be passed
explicity to the linker when building the testapp.

fdmanana 12:05:53 ~/git/hub/membase/couchstore2 (master)> make check
make  testapp
make[1]: Entering directory `/home/fdmanana/git/hub/membase/couchstore2'
  CC     tests/testapp-testapp.o
  CC     tests/testapp-file_merger_tests.o
  CC     tests/testapp-file_sorter_tests.o
  CC     tests/mapreduce/testapp-tests.o
  CC     tests/mapreduce/testapp-map.o
  CC     tests/mapreduce/testapp-reduce.o
  CC     tests/mapreduce/testapp-builtin.o
  CC     tests/views/testapp-tests.o
  CC     tests/views/testapp-collate_json_test.o
  CC     tests/views/testapp-index_headers.o
  CC     tests/views/testapp-bitmaps.o
  CC     tests/views/testapp-sorted_lists.o
  CC     tests/views/testapp-reductions.o
  CC     tests/views/testapp-keys.o
  CC     tests/views/testapp-values.o
  CC     tests/views/testapp-reducers.o
  CC     tests/views/testapp-spatial.o
  CCLD   testapp
./.libs/libcouchstore_tests.a(libcouchstore_tests_la-collate_json.o): In function `convertUTF8toUChar':
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:255: undefined reference to `ucnv_toUnicode_48'
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:231: undefined reference to `ucnv_open_48'
./.libs/libcouchstore_tests.a(libcouchstore_tests_la-collate_json.o): In function `compareUnicodeSlow':
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:204: undefined reference to `uiter_setUTF8_48'
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:205: undefined reference to `uiter_setUTF8_48'
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:207: undefined reference to `ucol_strcollIter_48'
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:194: undefined reference to `ucol_open_48'
./.libs/libcouchstore_tests.a(libcouchstore_tests_la-collate_json.o): In function `compareUnicode':
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:294: undefined reference to `ucol_strcoll_48'
/home/fdmanana/git/hub/membase/couchstore2/src/views/collate_json.c:271: undefined reference to `ucol_open_48'
collect2: ld returned 1 exit status
make[1]: *** [testapp] Error 1
make[1]: Leaving directory `/home/fdmanana/git/hub/membase/couchstore2'
make: *** [check-am] Error 2

Change-Id: I802a640c1a200ccec02c7656c490885465de1853
Reviewed-on: http://review.couchbase.org/30133
Tested-by: buildbot <build@couchbase.com>
Reviewed-by: Volker Mische <volker.mische@gmail.com>
Tested-by: Filipe David Borba Manana <fdmanana@gmail.com>