couchstore.py: Check for couchstore err in getContents()
Check the return value of couchstore_open_doc_with_docinfo(), and
raise an exception on failure.

This makes any errors in couchstore_open_doc_with_docinfo() explicit -
for example it will return

    couchstore.CouchStoreException: checksum fail

instead of the more generic:

    ValueError: NULL pointer access

in the event of a checksum failure in the file.

Change-Id: Ie5db90d25ecb5210b75c48c4ae027218696afc23
Reviewed-on: http://review.couchbase.org/84055
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Daniel Owen <owend@couchbase.com>